version: 0.2

phases:
  install:
    commands:
      - echo installing maven...
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo building application
      - mvn clean
      - mvn install
artifacts:
  files:
    - 'Dockerfile'
    - 'target/event-0.0.1-SNAPSHOT.jar'
