version: 0.2

phases:
  pre_build:
    commands:
      - echo Install IAM Authenticator
      - curl -o /usr/local/bin/aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.11.5/2018-12-06/bin/linux/amd64/aws-iam-authenticator
      - chmod 755 /usr/local/bin/aws-iam-authenticator
      - echo Update kubeconfig
      - aws eks --region $REGION update-kubeconfig --name $EKS_CLUSTER_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Create namespace
      - kubectl create ns $EKS_NAMESPACE || true
      - kubectl config set-context $(kubectl config current-context) --namespace=$EKS_NAMESPACE
      - echo Deploy image $ECR_REPO:$COMMIT_HASH
      - cat deploy/deployment.yml
      - cat deploy/service.yml
      - sed -i.'' "s/IMAGE_NAME:IMAGE_TAG/$ECR_REPO:$COMMIT_HASH/g" deploy/deployment.yml
      - kubectl apply -f deploy/deployment.yml -f deploy/service.yml
