apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service-deployment
  labels:
    app: events-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: events-service
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
        - name: events-service
          image: IMAGE_NAME:IMAGE_TAG
          ports:
            - containerPort: 8080
