apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-service-deployment
  labels:
    app: warehouse-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: warehouse-service
  template:
    metadata:
      labels:
        app: warehouse-service
    spec:
      containers:
        - name: warehouse-service
          image: IMAGE_NAME:IMAGE_TAG
          ports:
            - containerPort: 8080
